### ISSUE TITLE
As developer I want a re-usable package to use in various projects

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sharing-configs#1]
**Tasks**

* [x] Use default library setup to create basic layout
* [x] Make sure the Github actions are setup
* [x] Make the initial README on what's the idea
* [x] Move prototype code into the project
