### ISSUE TITLE
As developer, I want to easily connect my export function to sharing-configs

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sharing-configs#12]
For this, we'll create a mixin. A mixin already exists but it was created before we decided to abstract it away from Github, so we need to refactor it.

**Tasks**

* [x] Split up `sharing_configs/admin.py GitHubExportImportMixin` into `SharingConfigsExportMixin` and `SharingConfigsImportMixin`.
* [x] In the `SharingConfigsExportMixin`, add a function:
    ```
    get_sharing_configs_export_data(self, obj, **form_kwargs):
        raise NotImplemented
    ```
* [x] In the **testapp**, create an admin class that inherits this mixin, and override the `get_sharing_configs_export_data` function to return the data from #10
* [x] Refactor the `SharingConfigsExportMixin.export_to_github_view` to be called `sharing_configs_export_view` and make sure to pass `self.get_sharing_configs_export_data` to the form: `ExportToGithubForm(request.POST, instance=obj, initial=initial, export_func=self.get_sharing_configs_export_data)`
* [x] Refactor the `ExportToGithubForm.__init__` method to catch and store the `get_sharing_configs_export_data` function
* [x] Refactor the `ExportToGithubForm.save` method to call the export function (and do nothing with it for now)
* [x] Rename all Github-related variables/function to something without Github :)
