### ISSUE TITLE
As developer, I want to be able to set defaults for the project I use this library in

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sharing-configs#3]
We need to refactor the configuration that was created.

**Tasks**

* [x] Remove the `GithubConfig` model entirely
* [x] Add a new solo model (like GithubConfig) but called `SharingConfigsConfig`
* [x] Add fields to model: api_endpoint (urlfield), api_key (charfield 128), label (charfield 50), default_organisation (charfield optional, 100)
