### ISSUE TITLE
As developer, I want to hook easily into export functionality to export it to the sharing-configs-api

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sharing-configs#5]
**Tasks**

Sharing configurations works on 2 admin pages:

* [ ] Add abstract/base methods to "catch" exports and pass it to export to community
* [ ] Allow to easily add the "export to community" option to bulk actions
* [ ] Allow to easily add the "export to community" option to detail page (as button)
